apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.apps.name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.host.staticIP }}
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
    - secretName: tls-secret
  rules:
    - host: {{ .Values.host.activeuser }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.apps.name}}-service
              servicePort: {{ .Values.service.activeuser.port }}
    - host: {{ .Values.host.activeuser }}
      http:
        paths:
          - backend:
              serviceName: {{ .Chart.Name }}-service
              servicePort: {{ .Values.service.activeuser.port }}
